#!/bin/bash
echo "pass" > tmp
krun --output-mode raw -cHASHINFO="ListItem(64) ListItem(2305843009213693951) ListItem(314159) ListItem(0) ListItem(1000003)" -cOS="POSIX" -cDEBUG="true" -cPGM="$@" --cfg-parser "./parser" -cIMPORTLIB="fake-importlib.py" tmp
rm tmp
